### ISSUE TITLE
Build Not Working Correctly

### ISSUE THREAD

**Issue by mcfibb** [harningle/StataEditor#1]
Hey there -- thanks for making this! I'm having some trouble. I followed your instructions for installing StataEditor, Pywin32, etc. The scripts work great, as does the syntax highlighting, but I can't seem to get the system to build out my code. My best guess is it's a Python issue. Here is my console output:

```
DPI mode: per-monitor v2
startup, version: 4169 windows x64 channel: stable
executable: /C/Program Files/Sublime Text/sublime_text.exe
application: /C/Program Files/Sublime Text
working dir: /C/Program Files/Sublime Text
packages path: /C/Users/user/AppData/Roaming/Sublime Text/Packages
state path: /C/Users/user/AppData/Roaming/Sublime Text/Local
zip path: /C/Program Files/Sublime Text/Packages
zip path: /C/Users/user/AppData/Roaming/Sublime Text/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.118789
startup time: 0.167789
first paint time: 0.200789
reloading python 3.3 plugin StataEditor.CompletionsPlugin
Pywin32: Added 'win32'
Pywin32: Added 'win32/lib'
Pywin32: Added 'win32com'
Pywin32: Added 'win32comext'
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.html_print
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading python 3.3 plugin StataEditor.StataEditorPlugin
reloading plugin Default.keymap
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading python 3.3 plugin Pywin32.setup
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Package Control.plugin
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2024-04-09 10:16:10, next run at 2024-04-09 18:16:10 or after
Unable to open /C/Users/user/AppData/Roaming/Sublime Text/Packages/StataEditor/StataEditor.sublime-settings
Unable to open /C/Users/user/AppData/Roaming/Sublime Text/Packages/User/StataEditor.sublime-settings
reloading settings Packages/User/StataEditor.sublime-settings
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Sublime Text\Installed Packages\StataEditor.sublime-package\StataEditorPlugin.py", line 68, in StataAutomate
AttributeError: 'module' object has no attribute 'stata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Sublime Text\Packages\Pywin32\lib\x64\win32com\client\dynamic.py", line 89, in _GetGoodDispatch
    IDispatch = pythoncom.connect(IDispatch)
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 1493, in run_
    return self.run(edit, **args)
  File "C:\Users\user\AppData\Roaming\Sublime Text\Installed Packages\StataEditor.sublime-package\StataEditorPlugin.py", line 170, in run
  File "C:\Users\user\AppData\Roaming\Sublime Text\Installed Packages\StataEditor.sublime-package\StataEditorPlugin.py", line 76, in StataAutomate
  File "C:\Users\user\AppData\Roaming\Sublime Text\Packages\Pywin32\lib\x64\win32com\client\__init__.py", line 95, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx)
  File "C:\Users\user\AppData\Roaming\Sublime Text\Packages\Pywin32\lib\x64\win32com\client\dynamic.py", line 114, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "C:\Users\user\AppData\Roaming\Sublime Text\Packages\Pywin32\lib\x64\win32com\client\dynamic.py", line 91, in _GetGoodDispatch
    IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch)
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Sublime Text\Installed Packages\StataEditor.sublime-package\StataEditorPlugin.py", line 68, in StataAutomate
AttributeError: 'module' object has no attribute 'stata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Sublime Text\Packages\Pywin32\lib\x64\win32com\client\dynamic.py", line 89, in _GetGoodDispatch
    IDispatch = pythoncom.connect(IDispatch)
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 1493, in run_
    return self.run(edit, **args)
  File "C:\Users\user\AppData\Roaming\Sublime Text\Installed Packages\StataEditor.sublime-package\StataEditorPlugin.py", line 170, in run
  File "C:\Users\user\AppData\Roaming\Sublime Text\Installed Packages\StataEditor.sublime-package\StataEditorPlugin.py", line 76, in StataAutomate
  File "C:\Users\user\AppData\Roaming\Sublime Text\Packages\Pywin32\lib\x64\win32com\client\__init__.py", line 95, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx)
  File "C:\Users\user\AppData\Roaming\Sublime Text\Packages\Pywin32\lib\x64\win32com\client\dynamic.py", line 114, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "C:\Users\user\AppData\Roaming\Sublime Text\Packages\Pywin32\lib\x64\win32com\client\dynamic.py", line 91, in _GetGoodDispatch
    IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch)
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)
```

**Comment by harningle** [comment]
Sorry I'm not very sure with the problem, and have not used Stata for a while. Would you please check a few things:

* Preference > Package Settings > StataEditor > Settings - User: is `stata_path` correct? `stata_version` correct? It should look like `"stata_path": "C:/Program Files/Stata18/StataMP-64.exe",`, depending your Stata version/installation path
* ctrl + ` to go to console, run line by line:
    ```python
    import sublime
    import win32api

    settings_file = "StataEditor.sublime-settings"
    settings = sublime.load_settings(settings_file)  # Any error here?
    print(settings.get("stata_path"))                # Does it print your `stata_path` that you set above?
    
    win32api.WinExec(settings.get("stata_path"))     # Is your Stata opening?
    ```

**Comment by mcfibb** [comment]
Thanks so much. Yes to your first bullet. And for the second bullet, I run into problems on that second "import" command:

```
>>> import win32api
Traceback (most recent call last):
  File "__main__", line 1, in <module>
ModuleNotFoundError: No module named 'win32api'
```

**Comment by mcfibb** [comment]
Super help, thanks! I ran into an error on the import of win32api. Googled and saw someone with a similar issue, wherein Python 3.8 is the default for Sublime 4, not Python 3.3. I switched the version of Python in the command window and followed your steps again. Works as expected. I'll modify Sublime settings to default to 3.3.

**Comment by mcfibb** [comment]
Update: Still running into issues. I don't know if it's because the program requires 3.3 to be run, and if so, I can't figure out how to change that dependency, either in the StataEditor build file or the Python build file. Interestingly, I can get Stata to open, but code is not passed to it. Any ideas?

**Comment by harningle** [comment]
> Update: Still running into issues. I don't know if it's because the program requires 3.3 to be run, and if so, I can't figure out how to change that dependency, either in the StataEditor build file or the Python build file. Interestingly, I can get Stata to open, but code is not passed to it. Any ideas?

What's the error message now? (Or are there any errors or warnings when you run the stata code?)

**Comment by mcfibb** [comment]
Here's the output:

```Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Sublime Text\Installed Packages\StataEditor.sublime-package\StataEditorPlugin.py", line 68, in StataAutomate
AttributeError: 'module' object has no attribute 'stata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Sublime Text\Packages\Pywin32\lib\x64\win32com\client\dynamic.py", line 89, in _GetGoodDispatch
    IDispatch = pythoncom.connect(IDispatch)
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 1493, in run_
    return self.run(edit, **args)
  File "C:\Users\User\AppData\Roaming\Sublime Text\Installed Packages\StataEditor.sublime-package\StataEditorPlugin.py", line 170, in run
  File "C:\Users\User\AppData\Roaming\Sublime Text\Installed Packages\StataEditor.sublime-package\StataEditorPlugin.py", line 76, in StataAutomate
  File "C:\Users\User\AppData\Roaming\Sublime Text\Packages\Pywin32\lib\x64\win32com\client\__init__.py", line 95, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx)
  File "C:\Users\User\AppData\Roaming\Sublime Text\Packages\Pywin32\lib\x64\win32com\client\dynamic.py", line 114, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "C:\Users\User\AppData\Roaming\Sublime Text\Packages\Pywin32\lib\x64\win32com\client\dynamic.py", line 91, in _GetGoodDispatch
    IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch)
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)
```

**Comment by harningle** [comment]
`pywintypes.com_error: (-2147221005, xxxxx` suggests that python cannot find stata in the registry. Can you do [this](https://harningle.github.io/StataEditor/config/#register-the-stata-automation-type-library) to register the stata automation lib again?

**Comment by mcfibb** [comment]
Sure thing. Gimme a sec.

**Comment by mcfibb** [comment]
There it is! Fantastic -- thank you! I think the issue actually may have been that I wasn't running the Command Prompt as an administrator. Here's to following directions better next time.

Seriously, many thanks.
